### ISSUE TITLE
The approximate size of HInt dataset

### ISSUE THREAD

**Issue by Mine268** [ddshan/hint#1]
Can you please inform me of the size of the HInt dataset?

**Comment by ddshan** [comment]
Hi,

The [HInt_annotation_partial.zip](https://fouheylab.eecs.umich.edu/~dandans/projects/hamer/HInt_annotation_partial.zip) that you can download with the link we provide is ~3.6G on Linux.
The whole Hint (after adding ego4d frames) zip file size is  ~8.4G.

In terms of the number of images, here are the breakdown and total numbers for splits:
![image](https://github.com/ddshan/hint/assets/43507322/cde8b999-86ee-4971-8341-0968d4528d66)
